### ISSUE TITLE
new line getting added between lines in excerpt. / trim / formatting issue.

### ISSUE THREAD

**Issue by bharathganji** [wpsocio/wptelegram#60]
![image](https://user-images.githubusercontent.com/59326887/222313255-26244fc7-d598-4bed-a50c-029e2dce61b0.png)
![image](https://user-images.githubusercontent.com/59326887/222313331-f121ff70-26f8-4003-9224-09221ec5d205.png)

pls find above pics, u can understand clearly the issue, i can see this issue after 4.0.0. / 3 versions back i guess.
before that i haven't faced any problem.

pls fix this issue.

**Comment by irshadahmad21** [comment]
Thank you for reporting the issue @bharathganji 

Can you please share your Message Template set in Post to Telegram settings?

**Comment by bharathganji** [comment]
this is the exact template `📃 {post_title} | {post_date}

{post_excerpt}

View Details &amp; Apply | No Ads 🤞:
✅ {full_url}

🌟 *INVITE &amp; EARN* https://t.me/hirehuntindia/193

📌{tags}`

below pics may be unnecessary, but adding for fast debugging.
 
![image](https://user-images.githubusercontent.com/59326887/222316539-a8f6a0b9-b9bf-4ab0-8c77-54afe89ecb70.png)
![image](https://user-images.githubusercontent.com/59326887/222316588-6f8b0c93-c8a1-4268-9ca6-8abad2230166.png)
![image](https://user-images.githubusercontent.com/59326887/222316606-6b1f8fa8-3c78-4d3c-a1a7-da58de273cea.png)
![image](https://user-images.githubusercontent.com/59326887/222316635-7f664e2f-afee-4af0-8a23-5f6393742653.png)

**Comment by irshadahmad21** [comment]
Thank you for sharing those details. I'm working on a fix.

**Comment by irshadahmad21** [comment]
The issue has been fixed and an update has been released.

Thank you for reporting.
